In [2]:
from resnet import ResNet18
import numpy as np
from torchvision import datasets as ds
from torchvision import transforms as tfs
from torch.utils.data import DataLoader, Subset

def get_loader(bs, ntrain, nval):
    data_loc = '/home/.faa/data'
    trainset = ds.CIFAR10(root=data_loc, train=True, download=True, transform=tfs.ToTensor())
    testset = ds.CIFAR10(root=data_loc, train=False, download=True, transform=tfs.ToTensor())
    trainset_ = Subset(trainset, np.arange(0, ntrain))        
    valset = Subset(trainset, np.arange(ntrain, ntrain+nval))
    train = DataLoader(trainset_, bs, shuffle=True, pin_memory=True, drop_last = True)
    val = DataLoader(valset, bs, shuffle=True, pin_memory=True, drop_last = True) 
    test = DataLoader(testset, bs, shuffle=True, pin_memory=True, drop_last = True)
    return train, val, test
train, val, test = get_loader(10, 100, 100)

Files already downloaded and verified
Files already downloaded and verified


In [3]:
model = ResNet18(5, 3)
for x, y in train:
    break
prob = model(x)

In [11]:
import torch.nn.functional as F
probs = F.softmax(model(x), dim=1)

In [12]:
probs

tensor([[0.2742, 0.1823, 0.1483, 0.1563, 0.2390],
        [0.2802, 0.1519, 0.1434, 0.1635, 0.2610],
        [0.2601, 0.1474, 0.1690, 0.1796, 0.2438],
        [0.2923, 0.1879, 0.1057, 0.1513, 0.2629],
        [0.2245, 0.1542, 0.1607, 0.2090, 0.2515],
        [0.2385, 0.1768, 0.1877, 0.1604, 0.2367],
        [0.2746, 0.1666, 0.1714, 0.1535, 0.2338],
        [0.3148, 0.1718, 0.1320, 0.1608, 0.2205],
        [0.2878, 0.1569, 0.1601, 0.1609, 0.2343],
        [0.2780, 0.1810, 0.1231, 0.1373, 0.2805]], grad_fn=<SoftmaxBackward>)

In [13]:
action = probs.multinomial(num_samples=1).data

In [14]:
action

tensor([[1],
        [0],
        [2],
        [4],
        [0],
        [4],
        [0],
        [0],
        [2],
        [3]])

In [17]:
prob = probs[:, action[0,0]].view(1, -1)

tensor([[0.1823, 0.2742, 0.1483, 0.2390, 0.2742, 0.2390, 0.2742, 0.2742, 0.1483,
         0.1563, 0.1519, 0.2802, 0.1434, 0.2610, 0.2802, 0.2610, 0.2802, 0.2802,
         0.1434, 0.1635, 0.1474, 0.2601, 0.1690, 0.2438, 0.2601, 0.2438, 0.2601,
         0.2601, 0.1690, 0.1796, 0.1879, 0.2923, 0.1057, 0.2629, 0.2923, 0.2629,
         0.2923, 0.2923, 0.1057, 0.1513, 0.1542, 0.2245, 0.1607, 0.2515, 0.2245,
         0.2515, 0.2245, 0.2245, 0.1607, 0.2090, 0.1768, 0.2385, 0.1877, 0.2367,
         0.2385, 0.2367, 0.2385, 0.2385, 0.1877, 0.1604, 0.1666, 0.2746, 0.1714,
         0.2338, 0.2746, 0.2338, 0.2746, 0.2746, 0.1714, 0.1535, 0.1718, 0.3148,
         0.1320, 0.2205, 0.3148, 0.2205, 0.3148, 0.3148, 0.1320, 0.1608, 0.1569,
         0.2878, 0.1601, 0.2343, 0.2878, 0.2343, 0.2878, 0.2878, 0.1601, 0.1609,
         0.1810, 0.2780, 0.1231, 0.2805, 0.2780, 0.2805, 0.2780, 0.2780, 0.1231,
         0.1373]], grad_fn=<ViewBackward>)

In [16]:
action[0,0]

tensor(1)